type: default
memory: 512MB
filename: laser
checker_type: testlib
checker: checker.cpp
subtasks:
  - score: 100
    if: []
    id: 1
    type: min
    cases:
      - input: 1.in
        output: 1.out
      - input: 2.in
        output: 2.out
      - input: 3.in
        output: 3.out
      - input: 4.in
        output: 4.out
      - input: 5.in
        output: 5.out
      - input: 6.in
        output: 6.out
      - input: 7.in
        output: 7.out
      - input: 8.in
        output: 8.out
